/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { PresentationControls, useGLTF } from "@react-three/drei";
import { useControls } from "leva";

const Model = (props) => {
  const { nodes, materials } = useGLTF("/GamingRoom.glb");

  // these are the controls for the model
  const { upDown, rightLeft, nearFar, rotation } = useControls("Model", {
    upDown: {
      value: -1.7,
      step: 0.1,
    },
    rightLeft: {
      value: 0,
      step: 0.1,
    },
    nearFar: {
      value: 0.2,
      step: 0.1,
    },

    rotation: {
      value: [0, 0.7, 0],
      step: 0.1,
    },
  });

  return (
    // This is your model
    <group
      position={[rightLeft, upDown, nearFar]}
      rotation={rotation}
      {...props}
      dispose={null}
    >
      {/* This is for controls, for the ability to move the object around using mouse */}
      <PresentationControls>
        <mesh
          geometry={nodes.Table.geometry}
          material={materials.Table}
          position={[0, 1, -2.49]}
        >
          <mesh
            geometry={nodes.Stand001.geometry}
            material={materials.Stand}
            position={[0.83, -0.1, 0]}
            scale={0.32}
          />
          <mesh
            geometry={nodes.Stand002.geometry}
            material={materials.Stand}
            position={[-0.82, -0.45, 0]}
            scale={0.33}
          />
          <mesh
            geometry={nodes.Stand003.geometry}
            material={materials.Stand}
            position={[0.83, -0.45, 0]}
            scale={0.33}
          />
          <mesh
            geometry={nodes.Stand004.geometry}
            material={materials.Stand}
            position={[0.83, -0.63, 0]}
            scale={0.35}
          />
          <mesh
            geometry={nodes.Stand005.geometry}
            material={materials.Stand}
            position={[-0.82, -0.63, 0]}
            scale={0.35}
          />
          <mesh
            geometry={nodes.Stand006.geometry}
            material={materials.Stand}
            position={[-0.82, -0.1, 0]}
            scale={0.32}
          />
        </mesh>
        <mesh
          geometry={nodes.Ground.geometry}
          material={materials["Material.009"]}
          position={[0, 0.16, 0]}
          scale={3.24}
        />
        <group position={[0, 1.39, -2.66]}>
          <mesh geometry={nodes.Plane.geometry} material={materials.Monitor} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials.Screen} />
          <mesh
            geometry={nodes.arlene.geometry}
            material={materials.Chrome}
            position={[0, -0.15, 0.06]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Stand.geometry}
            material={materials.Monitor}
            position={[0, -0.17, -0.11]}
          />
        </group>
        <group
          position={[-0.68, 1.11, -2.69]}
          rotation={[-Math.PI, 1.44, 0]}
          scale={0.34}
        >
          <mesh
            geometry={nodes.Sphere001.geometry}
            material={materials.Speaker}
          />
          <mesh
            geometry={nodes.Sphere001_1.geometry}
            material={materials.Speaker_Fabric}
          />
          <mesh
            geometry={nodes.Sphere001_2.geometry}
            material={materials.Speakers_Color}
          />
        </group>
        <group position={[0, 1.08, -2.32]} scale={0.11}>
          <mesh
            geometry={nodes.Keyboard_1.geometry}
            material={materials.Keyboard}
          />
          <mesh
            geometry={nodes.Keyboard_2.geometry}
            material={materials.Keys}
          />
          <mesh
            geometry={nodes.Keys.geometry}
            material={materials.Keys}
            position={[1.97, -0.25, -0.92]}
            rotation={[0.11, 0, 0]}
          />
        </group>
        <mesh
          geometry={nodes.Wall_L.geometry}
          material={materials["Material.006"]}
          position={[0, 3.24, -3.24]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.24}
        />
        <mesh
          geometry={nodes.Wall_R.geometry}
          material={materials["Material.006"]}
          position={[3.24, 3.24, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={3.24}
        />
        <group
          position={[3.12, 2.95, -0.86]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={3.56}
        >
          <mesh
            geometry={nodes.Plane007.geometry}
            material={materials.Monitor}
          />
          <mesh
            geometry={nodes.Plane007_1.geometry}
            material={materials["Screen.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Table001.geometry}
          material={materials["Material.022"]}
          position={[-1.5, 0.52, 1.54]}
        >
          <mesh
            geometry={nodes.Cube016.geometry}
            material={materials["Material.017"]}
            position={[-0.33, -0.18, 0.62]}
          />
        </mesh>
        <mesh
          geometry={nodes.Chair.geometry}
          material={materials["Material.003"]}
          position={[0.13, 0.91, -1.33]}
          rotation={[Math.PI, -0.3, Math.PI]}
          scale={0.16}
        >
          <mesh
            geometry={nodes.Cube_4.geometry}
            material={materials["Material.003"]}
            position={[0, -1.21, 0.2]}
            scale={0.34}
          />
          <group position={[-1.96, -0.76, 1.16]} scale={0.13}>
            <mesh
              geometry={nodes.Cube009_1.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube009_2.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube003.geometry}
            material={materials.Material}
            position={[0, -1.62, 0.2]}
            scale={[0.28, 0.03, 0.28]}
          />
          <group position={[1.93, -0.76, 1.16]} scale={0.13}>
            <mesh
              geometry={nodes.Cube011_1.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube011_2.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube005.geometry}
            material={materials.Material}
            position={[0, -1.73, 0.83]}
            scale={0.18}
          />

          <mesh
            geometry={nodes.Cube007.geometry}
            material={materials.Material}
            position={[-1.42, -1.45, -0.62]}
            rotation={[-0.55, 0, 0]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.Material}
            position={[1.59, -0.34, -0.76]}
            scale={0.17}
          />
          <mesh
            geometry={nodes.Cube009.geometry}
            material={materials.Material}
            position={[1.62, -1.45, -0.62]}
            rotation={[-0.55, 0, 0]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Cube010.geometry}
            material={materials["Material.007"]}
            position={[0.02, 2.44, -0.66]}
            scale={0.37}
          />
          <mesh
            geometry={nodes.Cube011.geometry}
            material={materials["Material.008"]}
            position={[0, -0.21, 0.06]}
            scale={[0.95, 0.54, 0.54]}
          />
          <mesh
            geometry={nodes.Cube012.geometry}
            material={materials["Material.003"]}
            position={[1.93, -0.76, 1.16]}
            scale={0.13}
          />
          <mesh
            geometry={nodes.Cube013.geometry}
            material={materials["Material.003"]}
            position={[-1.96, -0.76, 1.16]}
            scale={0.13}
          />
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={materials.Material}
            position={[0, -0.71, 0.51]}
            rotation={[-0.2, 0, 0]}
            scale={2.25}
          />
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials.Material}
            position={[0, 0.06, -0.79]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.12}
          />
          <group
            position={[0, -0.72, 0.36]}
            rotation={[0, -0.31, 0]}
            scale={1.45}
          >
            <mesh
              geometry={nodes.Cylinder005.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cylinder005_1.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder003.geometry}
            material={materials.Material}
            position={[-1.57, -1.27, -0.69]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.53}
          />
          <mesh
            geometry={nodes.Cylinder004.geometry}
            material={materials.Material}
            position={[1.59, -1.27, -0.69]}
            rotation={[Math.PI, 0, Math.PI / 2]}
            scale={0.53}
          />

          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials["Material.002"]}
            position={[-1.02, -1.78, 0.18]}
            scale={2.23}
          />
          <mesh
            geometry={nodes.Plane003.geometry}
            material={materials["Material.003"]}
            position={[0, -1.52, 1.07]}
            rotation={[-0.04, 0, 0]}
            scale={2.23}
          />
          <mesh
            geometry={nodes.Plane004.geometry}
            material={materials["Material.005"]}
            position={[0, -4.64, 0.2]}
            scale={2.23}
          />
        </mesh>
        <group position={[-0.5, 0.47, -2.48]} scale={[0.14, 0.31, 0.31]}>
          <mesh geometry={nodes.Cube.geometry} material={materials.Base} />
          <mesh
            geometry={nodes.Cube_1.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Cube_2.geometry}
            material={materials.Keyboard}
          />
          <mesh
            geometry={nodes.Cube_3.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[0, 3.11, -3.24]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Plane008.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Plane008_1.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group position={[1.43, 0.79, 1.26]} scale={0.29}>
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Cube022_1.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            geometry={nodes.Cube022_2.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.Cube022_3.geometry}
            material={materials["Material.019"]}
          />
        </group>
      </PresentationControls>
    </group>
  );
};

useGLTF.preload("/GamingRoom.glb");
export default Model;
